CREATE TABLE customer (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    mobile_number VARCHAR(20),
    pwd VARCHAR(255) NOT NULL,
    role VARCHAR(50),
    create_dt DATE,
    CONSTRAINT uk_customer_email UNIQUE (email)
);

CREATE TABLE authorities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    customer_id BIGINT NOT NULL,
    CONSTRAINT fk_authorities_customer
        FOREIGN KEY (customer_id) REFERENCES customer (customer_id)
);

CREATE INDEX idx_authorities_customer_id ON authorities (customer_id);
